import pandas as pd
import joblib

# Eğitilmiş modeli yükle
model = joblib.load("C:/Software/PyCharm/pythonProjects/mLDataExtraction/mlModells/GradientBoostingRegressor_model.pkl")

# Tahmin için girdi verisi oluştur
girdi_verisi = pd.DataFrame({
     "marka_Aeropostale": [False],
    "marka_Alberto Guardiani": [False],
    "marka_Armani Exchange": [False],
    "marka_Asics": [False],
    "marka_Benetton": [False],
    "marka_Buckhead": [False],
    "marka_Bulldozer": [False],
    "marka_Calvin Klein": [False],
    "marka_Camper": [False],
    "marka_Caterpillar": [False],
    "marka_Clarks": [False],
    "marka_Columbia": [False],
    "marka_Converse": [False],
    "marka_Cotton Bar": [False],
    "marka_Dc Shoes": [False],
    "marka_Discovery Expedition": [False],
    "marka_Dunlop": [False],
    "marka_Ecco": [False],
    "marka_F By Fabrika": [False],
    "marka_Fabrika": [False],
    "marka_Fabrika Comfort": [False],
    "marka_Flower Mountain": [False],
    "marka_George Hogg": [False],
    "marka_Greyder": [False],
    "marka_Guess": [False],
    "marka_Hammer Jack": [False],
    "marka_Harley Davidson": [False],
    "marka_Helly Hansen": [False],
    "marka_Hummel": [False],
    "marka_Hush Puppies": [False],
    "marka_Igor": [False],
    "marka_Jack Wolfskin": [False],
    "marka_Joma": [False],
    "marka_Kappa": [False],
    "marka_Karl Lagerfeld": [False],
    "marka_Keen": [False],
    "marka_Legero": [False],
    "marka_Lumberjack": [True],
    "marka_Merrell": [False],
    "marka_New Balance": [False],
    "marka_Nike": [False],
    "marka_Pierre Cardin": [False],
    "marka_Puma": [False],
    "marka_Reebok": [False],
    "marka_Salomon": [False],
    "marka_Sebago": [False],
    "marka_Skechers": [False],
    "marka_Superga": [False],
    "marka_The North Face": [False],
    "marka_Timberland": [False],
    "marka_Tommy Hilfiger": [False],
    "marka_U.S. Polo Assn.": [False],
    "marka_Ugg": [False],
    "marka_Under Armour": [False],
    "marka_Vans": [False],
    "marka_Versace Jeans Couture": [False],
    "marka_Vince Camuto": [False],
    "marka_adidas": [False],
    "taban_EVA": [False],
    "taban_Faylon": [False],
    "taban_Kauçuk": [False],
    "taban_Mantar": [False],
    "taban_Neolit": [False],
    "taban_PVC": [False],
    "taban_Phylon": [False],
    "taban_Poli": [False],
    "taban_Poliüretan": [False],
    "taban_Poliüretan/TPU": [False],
    "taban_Sentetik": [False],
    "taban_TPU": [False],
    "taban_Tekstil": [False],
    "taban_Termo": [False],
    "taban_Termoplastik": [False],
    "taban_kauçuk": [True],
    "taban_taban": [False],
    "materyal_Deri": [False],
    "materyal_File": [False],
    "materyal_Kanvas": [False],
    "materyal_Mesh": [False],
    "materyal_Microfiber": [True],
    "materyal_Naylon": [False],
    "materyal_Nubuk": [False],
    "materyal_PU": [False],
    "materyal_PVC": [False],
    "materyal_Poliüretan": [False],
    "materyal_Polyester": [False],
    "materyal_Sentetik": [False],
    "materyal_Süet": [False],
    "materyal_Tekstil": [False],
    "materyal_deri": [False],
    "menşei_Almanya": [False],
    "menşei_Bangladeş": [False],
    "menşei_Cum.": [False],
    "menşei_Endonezya": [False],
    "menşei_Hindistan": [False],
    "menşei_Kamboçya": [False],
    "menşei_Myanmar": [False],
    "menşei_Portekiz": [False],
    "menşei_Romanya": [False],
    "menşei_Slovakya": [False],
    "menşei_Tayland": [False],
    "menşei_Tayvan": [False],
    "menşei_Türkiye": [True],
    "menşei_Vietnam": [False],
    "menşei_Çin": [False],
    "menşei_İspanya": [False],
    "cinsiyet_erkek": [False],
    "cinsiyet_kadın": [False],
    "tip_ayakkabı": [False],
    "tip_bot": [True]
})

# Tahmin yap
tahmin = model.predict(girdi_verisi)
print("Tahmin edilen fiyat:", tahmin)
